In [ ]:
!pip install -q geopy
!pip install -q pyproj

# basic utilities
import json
import requests
import pandas as pd
import pprint
import time

# reverse geocoding utilities
from geopy.geocoders import Nominatim

# geography projection utilities
import pyproj
from shapely.ops import transform
from shapely.geometry import Point
from functools import partial

     |████████████████████████████████| 6.3 MB 4.4 MB/s

In [ ]:
#%cd ..
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
!ln -s /content/gdrive/MyDrive/ /mydrive
!ls /mydrive

'2020 slides'
 2021-online-language-offline-impact-main
 An_Xception_Based_Convolutional_Neural_Network_for_Scene_Image_Classification_with_Transfer_Learning.pdf
'API key'
'Application for Lease- Form for Email (Applicant) (1).gdoc'
'Application for Lease- Form for Email (Applicant).gdoc'
'Application for Lease- Form for Email (Applicant).pdf'
'Colab Notebooks'
'CV -Xizhi Wu.pdf'
'FOW Documents'
 MyDrive
'NT15 LEASE 2021.gdoc'
'NT15 LEASE 2021.pdf'
'Review Group 9.gdoc'
 Xizhi_Wu_UnderGrad_Transcript.pdf
 教授资格证身份证.pdf

In [ ]:
%cd gdrive/MyDrive/2021-online-language-offline-impact-main

/content/gdrive/MyDrive/2021-online-language-offline-impact-main

In [ ]:
!ls

 a0529-a0611_UK		       dataframe_result_csv_UK
 a0529-a0611_US		       Github
 ccc_compiled.csv	       heatmap529_UK.ipynb
 csv			       heatmap530.ipynb
 csv.zip		       Heat_Map_Online_language.ipynb
 dataframe_csv		       __MACOSX
 dataframe_csv_EU	       mapping_UK
 dataframe_csv_UK	       mapping_US
 dataframe_result_529_UK.csv   non_violant1.csv
 dataframe_result_530_UK.csv   non_violant2.csv
 dataframe_result_531_UK.csv   UK
 dataframe_result_csv	       violant.csv
 dataframe_result_csv_EU      '新建 Microsoft PowerPoint 演示文稿.pptx'

In [ ]:
import os
import collections
import ast
import pandas as pd
import numpy as np
from scipy import stats
from datetime import datetime, timedelta
import spacy
import tensorflow as tf
import tensorflow_hub as hub
from tensorflow.keras import layers
#from bert import tokenization
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
import matplotlib.pyplot as plt

In [ ]:
dataframe_path_530 = 'dataframe_csv/dataframe0611.csv'

In [ ]:
dataframe_530 = pd.read_csv(dataframe_path_530)

In [ ]:
dataframe_530=pd.DataFrame(dataframe_530,columns=['0','1'])

In [ ]:
dataframe_530

                          0     1
0               minneapolis  1761
1                   america   479
2                      u.s.   360
3                   houston   344
4                        us   300
...                     ...   ...
1358            richmond va     1
1359  the city of jerusalem     1
1360      the city of peace     1
1361              watertown     1
1362                  bryan     1

[1363 rows x 2 columns]

In [ ]:
dataframe_530.shape[1]

2

In [ ]:
columns2=['City','Number']

In [ ]:
#len(columns1)
len(columns2)

2

In [ ]:
dataframe_530.columns=columns2

In [ ]:
dataframe_530

                       City  Number
0               minneapolis    1761
1                   america     479
2                      u.s.     360
3                   houston     344
4                        us     300
...                     ...     ...
1358            richmond va       1
1359  the city of jerusalem       1
1360      the city of peace       1
1361              watertown       1
1362                  bryan       1

[1363 rows x 2 columns]

In [ ]:
dataframe_530['Mapping']=None
dataframe_530['Latitude']=None
dataframe_530['Longtitude']=None

In [ ]:
#for i in dataframe_530['Mapping']:
#  if(i==None):
#    print('Y')

In [ ]:
dataframe_530

                       City  Number Mapping Latitude Longtitude
0               minneapolis    1761    None     None       None
1                   america     479    None     None       None
2                      u.s.     360    None     None       None
3                   houston     344    None     None       None
4                        us     300    None     None       None
...                     ...     ...     ...      ...        ...
1358            richmond va       1    None     None       None
1359  the city of jerusalem       1    None     None       None
1360      the city of peace       1    None     None       None
1361              watertown       1    None     None       None
1362                  bryan       1    None     None       None

[1363 rows x 5 columns]

In [ ]:
counter=2
print(dataframe_530['City'][counter])

u.s.

In [ ]:
from geopy.exc import GeocoderTimedOut
counter=0
for i in dataframe_530['City']:
  #search_string=dataframe_529['City'][i]
  geolocator = Nominatim(user_agent="address_development")
  try:
    location = geolocator.geocode(i,timeout=30)
    if(location==None):
      counter+=1
      time.sleep(1)
      continue
    else:
      dataframe_530['Latitude'][counter]=location.latitude
      dataframe_530['Longtitude'][counter]=location.longitude
      dataframe_530['Mapping'][counter]=location.address
      time.sleep(1)
    counter+=1
  except GeocoderTimedOut as e:
    print("Error: geocode failed on input %s with message %s"%(Location, e.msg))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [ ]:
dataframe_530

                       City  Number  ... Latitude Longtitude
0               minneapolis    1761  ...  44.9773   -93.2655
1                   america     479  ...  51.4371     5.9799
2                      u.s.     360  ...  48.6841    9.00958
3                   houston     344  ...  29.7589   -95.3677
4                        us     300  ...  39.7837   -100.446
...                     ...     ...  ...      ...        ...
1358            richmond va       1  ... -32.8652    151.501
1359  the city of jerusalem       1  ...  52.9493   -1.15265
1360      the city of peace       1  ...  51.5131  -0.056667
1361              watertown       1  ...  42.3709   -71.1828
1362                  bryan       1  ...  30.6744     -96.37

[1363 rows x 5 columns]

In [ ]:
%cd mapping_US

/content/gdrive/My Drive/2021-online-language-offline-impact-main/mapping_US

In [ ]:
!ls

 Country.txt			 dataframe0609_post_remove.csv
 dataframe0529_post.csv		 dataframe0610_post.csv
 dataframe0529_post_remove.csv	 dataframe0610_post_remove.csv
 dataframe0530_post.csv		 dataframe0611_post.csv
 dataframe0530_post_remove.csv	 dataframe0611_post_remove.csv
 dataframe0531_post.csv		 dataframe_mapping
 dataframe0531_post_remove.csv	 dataframe_mapping_0529.csv
 dataframe0601_post.csv		 dataframe_mapping_0530.csv
 dataframe0601_post_remove.csv	 dataframe_mapping_0531.csv
 dataframe0602_post.csv		 dataframe_mapping_0601.csv
 dataframe0602_post_remove.csv	 dataframe_mapping_0602.csv
 dataframe0603_post.csv		 dataframe_mapping_0603.csv
 dataframe0603_post_remove.csv	 dataframe_mapping_0604.csv
 dataframe0604_post.csv		 dataframe_mapping_0605.csv
 dataframe0604_post_remove.csv	 dataframe_mapping_0606.csv
 dataframe0605_post.csv		 dataframe_mapping_0607.csv
 dataframe0605_post_remove.csv	 dataframe_mapping_0608.csv
 dataframe0606_post.csv		 dataframe_mapping_0609.csv
 dataframe0606_post_remove.csv	 datarframe_post
 dataframe0607_post.csv		'mapping_US_Cities_Only (1).zip'
 dataframe0607_post_remove.csv	 mapping_US_Cities_Only.zip
 dataframe0608_post.csv		 post_specific_mapping_US.zip
 dataframe0608_post_remove.csv	 states.csv
 dataframe0609_post.csv

In [ ]:
dataframe_530.to_csv('dataframe_mapping_0611.csv')